// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc157.ProtoBot2017.subsystems;

import org.usfirst.frc157.ProtoBot2017.RobotMap; 
import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Relay;


/**
 *
 */
public class Gate extends Subsystem {
    
    /// gate uses a pwm signal on spike 
    /// command = on or off

    private final Relay gateRelay = RobotMap.gateRelay;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    private final double Speed= 0.5; 

    public enum gateCommand
    {
        OPEN,
        CLOSED,
        OFF
    }

        
    public Gate()
    {
        System.out.println("Gate:GATE()");
        
        gateRelay.set(Relay.Value.kOn);
    }        
   
    
    public void OPEN()
    {
        gateRelay.set(Relay.Value.kForward);
    }

    public void CLOSE()
    {
        
        gateRelay.set(Relay.Value.kReverse);
    }

    public void OFF ()
    {
              gateRelay.set(Relay.Value.kOff);
    }
    
    
    @Override
    protected void initDefaultCommand()
    {
        // TODO Auto-generated method stub
        
    }
}
    
