// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc157.ProtoBot2017.subsystems;

import org.usfirst.frc157.ProtoBot2017.Robot;
import org.usfirst.frc157.ProtoBot2017.RobotMap;  
import org.usfirst.frc157.ProtoBot2017.commands.*;
import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Sendable;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.DigitalInput;


/**
 *
 */
public class GearBridge extends Subsystem {

    private final double UP_SPEED  = 0.40;
    private final double DOWN_SPEED = 0.15;
    private final CANTalon GearBridgeMotorLeft = RobotMap.GearBridgeMotorLeft;
    private final CANTalon GearBridgeMotorRght = RobotMap.GearBridgeMotorRght;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    // Limit Switches
    protected DigitalInput upLimitSwitchLeft;
    protected DigitalInput downLimitSwitchLeft;
    protected DigitalInput upLimitSwitchRight;
    protected DigitalInput downLimitSwitchRight;

    public enum GearBridgeCommand
    {
        RAISE,
        LOWER,
        IDLE
    }
        
    public GearBridge()
    {
        System.out.println("Gear: Gear()");
        upLimitSwitchLeft = new DigitalInput(0);
        downLimitSwitchLeft = new DigitalInput(1);
        upLimitSwitchRight = new DigitalInput(2);
        downLimitSwitchRight = new DigitalInput(3);
        
        GearBridgeMotorLeft.changeControlMode(CANTalon.TalonControlMode.PercentVbus);
        GearBridgeMotorRght.changeControlMode(CANTalon.TalonControlMode.PercentVbus);

    }        
   
    
    public boolean isDown()
    {
        //int test = 1 / 0;
        boolean testLeft;
        boolean testRight;
        boolean answer;
       // System.out.println("GearBridge: isDown()");
        testLeft = downLimitSwitchLeft.get();
        testRight = downLimitSwitchRight.get();
      
        if (testLeft == true && testRight == true )
        {
           answer = true;
        //   System.out.println("isDown: true");
        }
        else
        {
            answer = false;
      //      System.out.println("isDown: false");
        }
        return answer;
    }

    public boolean isUp() 
    {
        boolean testLeft;
        boolean testRight;
        boolean answer;
     //   System.out.println("GearBridge: isUp()");
        testLeft = upLimitSwitchLeft.get();
        testRight = upLimitSwitchRight.get();
      
        if (testLeft == true && testRight == true )
        {
           answer = true;
          // System.out.println("isUp: true");
        }
        else
        {
            answer = false;
            //System.out.println("isUp: false");
        }
        return answer;
    }
    
    public void lower()
    {
        boolean testLeft;
        boolean testRight;
        boolean answer;
        testLeft = downLimitSwitchLeft.get();
        
         if (testLeft == true)
         {
             GearBridgeMotorLeft.set(0.0);         
         }
         else
         {
             GearBridgeMotorLeft.set(-DOWN_SPEED);
         }
         
     
         testRight = downLimitSwitchRight.get();
         
         if (testRight == true)
         {
             GearBridgeMotorRght.set(0.0);         
         }
         else
         {
             GearBridgeMotorRght.set(-DOWN_SPEED);
         }
     
     }
    
    
    public void raise()
    {
       boolean testLeft;
       boolean testRight;
       boolean answer;
       testLeft = upLimitSwitchLeft.get();

        if (testLeft == true)
        {
            GearBridgeMotorLeft.set(0.0);         
        }
        else
        {
            GearBridgeMotorLeft.set(UP_SPEED);
        }
        
    
        testRight = upLimitSwitchRight.get();
    
        if (testRight == true)
        {
            GearBridgeMotorRght.set(0.0);         
        }
        else
        {
            GearBridgeMotorRght.set(UP_SPEED);
        }
    
    }
    
    public void idle()
    {
        GearBridgeMotorLeft.set(0.0);   
        GearBridgeMotorRght.set(0.0); 
    }
    
    @Override
    public void initDefaultCommand()
    { 
        setDefaultCommand(new GearBridgeLowerCommand());
    }
}
    
