// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc157.ProtoBot2017.subsystems;

import org.usfirst.frc157.ProtoBot2017.RobotMap;
import org.usfirst.frc157.ProtoBot2017.commands.*;
import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Sendable;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.DigitalInput;


/**
 *
 */
public class Gear extends Subsystem {

    private final double OPEN_SPEED  = 0.40;
    private final double CLOSE_SPEED = 0.15;
    private final CANTalon gearMotorLeft = RobotMap.gearMotorLeft;
    private final CANTalon gearMotorRight = RobotMap.gearMotorRight;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    // Limit Switches
    protected DigitalInput openLimitSwitchLeft;
    protected DigitalInput closeLimitSwitchLeft;
    protected DigitalInput openLimitSwitchRight;
    protected DigitalInput closeLimitSwitchRight;

    public enum GearCommand
    {
        OPEN,
        CLOSE,
        IDLE
    }
        
    public Gear()
    {
        System.out.println("Gear: Gear()");
        openLimitSwitchLeft = new DigitalInput(4); 
        closeLimitSwitchLeft = new DigitalInput(5); 
        openLimitSwitchRight = new DigitalInput(6);
        closeLimitSwitchRight = new DigitalInput(7);
        
        gearMotorLeft.changeControlMode(CANTalon.TalonControlMode.PercentVbus);
        gearMotorRight.changeControlMode(CANTalon.TalonControlMode.PercentVbus);

    }        
   
    
    public boolean isClosed()
    {
        //int test = 1 / 0;
        boolean testLeft;
        boolean testRight;
        boolean answer;
        System.out.println("Gear: isClosed()");
        testLeft = closeLimitSwitchLeft.get();
        testRight = closeLimitSwitchRight.get();
      
        if (testLeft == true && testRight == true )
        {
           answer = true;
           System.out.println("is closed: true");
        }
        else
        {
            answer = false;
            System.out.println("is closed: false");
        }
        return answer;
    }

    public boolean isOpen() 
    {
        boolean testLeft;
        boolean testRight;
        boolean answer;
        System.out.println("Gear: isopen()");
        testLeft = openLimitSwitchLeft.get();
        testRight = openLimitSwitchRight.get();
      
        if (testLeft == true && testRight == true )
        {
           answer = true;
           System.out.println("is open: true");
        }
        else
        {
            answer = false;
            System.out.println("is open: false");
        }
        return answer;
    }
    
    public void close()
    {
        boolean testLeft;
        boolean testRight;
        boolean answer;
        testLeft = closeLimitSwitchLeft.get();

         if (testLeft == true)
         {
             gearMotorLeft.set(0.0);         
         }
         else
         {
             gearMotorLeft.set(-CLOSE_SPEED);
         }
         
     
         testRight = closeLimitSwitchRight.get();
     
         if (testRight == true)
         {
             gearMotorRight.set(0.0);         
         }
         else
         {
             gearMotorRight.set(-CLOSE_SPEED);
         }
     
     }
    
    
    public void open()
    {
       boolean testLeft;
       boolean testRight;
       boolean answer;
       testLeft = openLimitSwitchLeft.get();

        if (testLeft == true)
        {
            gearMotorLeft.set(0.0);         
        }
        else
        {
            gearMotorLeft.set(OPEN_SPEED);
        }
        
    
        testRight = openLimitSwitchRight.get();
    
        if (testRight == true)
        {
            gearMotorRight.set(0.0);         
        }
        else
        {
            gearMotorRight.set(OPEN_SPEED);
        }
    
    }
    
    public void idle()
    {
        gearMotorLeft.set(0.0);   
        gearMotorRight.set(0.0); 
    }
    
    @Override
    protected void initDefaultCommand()
    {
        // TODO Auto-generated method stub
        
    }
}
    
