// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc157.ProtoBot2017.commands;
import edu.wpi.first.wpilibj.Timer; 
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc157.ProtoBot2017.Robot;

/**
 *
 */
public class AutoTurn extends Command
{
    private boolean finished = false;

    
	private double driveTime; // seconds
	private double rotationSpeed; // fraction of full speed
	
	private double autoDriveStartTime; // seconds

	public AutoTurn(double driveTime, double rotationSpeed) {
		this.driveTime = driveTime;
		this.rotationSpeed= rotationSpeed;
    }

    // Called just before this Command runs the first time
    protected void initialize()
    {
    	autoDriveStartTime = Timer.getFPGATimestamp();
    	Robot.drive.driveBot(0,driveTime, rotationSpeed);
    	System.out.println("STARTING AUTO @" + autoDriveStartTime);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() 
    {
    	// once robot has been driving for driveTime, declare finished
    	if(Timer.getFPGATimestamp() > (autoDriveStartTime + driveTime))
    	{
    		finished=true;
    	}
    }
   // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return finished;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.drive.driveBot(0, 0, 0);
    	System.out.println("EDNING AUTO @" + Timer.getFPGATimestamp());
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.drive.driveBot(0, 0, 0);
    	System.out.println("EDNING AUTO @" + Timer.getFPGATimestamp());
    }
}
