// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc157.ProtoBot2017.commands;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc157.ProtoBot2017.commands.AutoDriveSpeedForTime;
//import org.usfirst.frc157.FRC2016.commands.PrintButton;
import org.usfirst.frc157.ProtoBot2017.Robot;
import org.usfirst.frc157.ProtoBot2017.RobotMap;
import org.usfirst.frc157.ProtoBot2017.AnalogSelectSwitch.SwitchPosition;
import com.ctre.CANTalon;

/**
 *
 */
public class AutonomousCommand extends Command {

   
    public AutonomousCommand() {
    	requires(Robot.drive);

		SwitchPosition switchPosition = RobotMap.modeSelect.getPosition();

		System.out.println("Autonomous Switch: " + switchPosition);
		switch(switchPosition)
		{
		/*
		 * Autonomuous commands 
		 * drive forward 6ft(done)
		 * drive forward 4 ft reverse 2ft 
		 * drive forward 2-3 ft turn left camera shoot 
		 * drive to deliver gear
		 */
    		case POSITION_0:
    		{
                System.out.println("\n*********************************\n");
                System.out.println("Autonomous Position 0");
                // do nothing case 
                break;
    		}
    		case POSITION_1:
    		{
    			System.out.println("\n*********************************\n");
    			System.out.println("Autonomous Position 1");
    			// Drive forward 6 ft
    			new AutoDriveSpeedForTime(0.5,5.0);
    		}
    		case POSITION_2:
    		{
    			System.out.println("\n*********************************\n");
    			System.out.println("Autonomous Position 2");
    			//drive forward 4 fft backup 2 
    			new AutoDriveSpeedForTime(0.5,2.5);
    			new AutoDriveSpeedForTime(0.5,1);
    			break;
    		}
    		case POSITION_3:
    		{
    			System.out.println("\n*********************************\n");
    			System.out.println("Autonomous Position 3");
    			new AutoDriveSpeedForTime(0.5,2.5);
    			new AutoTurn(0.5,.5);
    			//new  AutoALigntoSHoo
    			break;
    		}
    		case POSITION_4:
            {
                System.out.println("\n*********************************\n");
                System.out.println("Autonomous Position 4");
                //drive to gear
                 
                break;
            }
    		case POSITION_5:
    		{
    			System.out.println("\n*********************************\n");
    			System.out.println("Autonomous Position 5");

    			//addSequential(new PrintButton(">>> Autonomous Position 5"));
    			//unimplemented
    			break;
    		}
		}

    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() 
    {
       // Robot.drive.DriveForwardForTime(100);
     
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
